### ISSUE TITLE
One Makefile to rule them all....

### ISSUE THREAD

**Issue by andrewgtp** [andrewgtp/algorithms-c#11]
- Cleanup
- Readability
- Modern makefile practices  - use example from online, another book?
- Consider header files, library files, utilities
- Consider file/folder structure

**Comment by rpappalax** [comment]
One Makefile to rule them all, One Makefile to find them,
One Makefile to bring them all, and in the repo bind them,
In the Land of Github where the Algorithms lie 
![theprecious](https://cloud.githubusercontent.com/assets/3699494/17085331/193058b8-518a-11e6-8c82-140794e874fb.png)
